### ISSUE TITLE
User feedback

### ISSUE THREAD

**Issue by daattali** [bcgov/WES_engagement_states#18]
(Waiting to see if I get a new contract because my previous contract is expired - if/when I do, I'll add all the feedback items here)

**Comment by daattali** [comment]
This is all the actionable feedback from the MS Word doc that I received, organized into tasks that can be achieved vs tasks that need clarification.

# Clearly defined and achievable tasks

- [x] A. Rmd report: move the matrix and first paragraph to Methods tab (@najsaqib)
- [x] B. Rmd report: Move the final section (list at the end starting from “Four types pf migration…) and adjust the language so it matches how the groups are defined in the other tabs (@najsaqib)
- [x] C. Show both 2013 and 2015 data in the engagement tab
- [x] D. Revise main title to BC Public Service Work Environment Survey (WES)
- [x] E. Six engagement states will confuse people - combine "engaged" with "moderately engaged" and "disengaged" with "minimally disengaged" (Need confirmation from @MonkmanMH) 
- [x] F. Drop the text "Engagement state" from the engagement plot legend
- [x] G. Make the variable names that get shown in the table more user friendly
- [x] H. Don't show the satisfaction and commitment values in the engagement data table 
- [x] I. In the engagement data table, add the `%` symbol to the Percent column
- [x] J. In the data tables, drop the "Organization" column is only one is shown
- [x] K. Make sure organizations with a comma (`,`) are exported correctly
- [x] L. Add thousands-separator comma in numbers in the data tables
- [x] M. Rename "Migration Analysis" tab
- [x] N. Colours in sankey migration plot should match exactly colours from engagement plot (Can take place after E. gets resolved)
- [x] O. Add "2013 State" and "2015 State" titles above the sankey plot
- [x] P. Migration data table: add column that shows percent for each row (assuming the total is from 2015 state)
- [x] Q. Migration data: Rename "Incomplete" to "Non Respondent"
- [x] R. Migration data: Rename "N/A" to "Not in Population"
- [x] S. Migration data: add the words "Unhappily" and "Happily" to the states
- [x] T. Migration data: show all 36 rows without pagination support
- [x] U. Add text to the Methods tab based on the suggestion given in the MS Word document

# Tasks that require clarification

- [x] Gov2.0 look and feel – fonts/heading size, styles and colours should match this http://www2.gov.bc.ca/gov/content/about-gov-bc-ca/web-presence/developers-guide/css-elements (**Simply changing the font and size is easy, but I'll need more details on the wanted colour scheme and other UI elements**)
- [x] Copyright and other bumpf (see bottom of BC Stats website for reference)? (**We need exact text**)
- [x] Should add BC Stats work environment email for questions and feedback (**I feel like this should go in the Method tab? I need to know what email to use and the text to use**) 
- [ ] Add some description to what the engagement plot/migration plot means and how to interpret it (**Please provide us with the text you want**) (update: descriptive info was added to the migration plot, but not to the engagement plot)
- [ ] This task I need to  understand better: http://i.imgur.com/NRMzjzw.png What exactly is this table, and where should it be displayed?

# Future tasks

- [ ] Restrict Access to certain organizations but let all have access to “all” (**This can only happen after the app gets deployed to a server that supports authentication**)
- [ ] Look into exporting the entire visible web page to PDF (**From previous experience, this isn't something that is easily done, but if it's extremely important I can take a look again when all else is done**)

**Comment by daattali** [comment]
@najsaqib could you tackle the first two items in the list since they're part of the Rmd stuff? And whenever you have time (next week/the week after/whenever), do you think you could get clarification about the few tasks I put under the "require clarification"?

@MonkmanMH do you agree we should simplify the engagement states into only 4 states instead of 6? I'll hold off on that task until you approve/disapprove

**Comment by MonkmanMH** [comment]
@daattali -- I just checked with our colleague Angela, and I can confirm that we will collapse the engagement states into the 4 categories. This will make it consistent across both the bubble and sankey plots

**Comment by daattali** [comment]
Thanks for keeping an eye on all every time I mention you on Github!

---
R-Shiny Consultant
http://deanattali.com/shiny

**Comment by MonkmanMH** [comment]
Ha ha! I think I check github more often than some of my email accounts now...and I'm just trying to do my part to keep this thing going.

Under **Tasks that require clarification**:

* copyright and other bumpf: yes, the Methods tab(s)
* email and other contact info: yes, the Methods tab(s)
* the inclusion of Elections BC is a function of the mock data set; this will be addressed with the use of the final data (heads up @najsaqib and @jimmartell )
* interpretation text: @najsaqib can connect with Angela for this
* bonus table: this is a summary of the table that currently appears on the migration page ... another topic for @najsaqib connect with Angela on

**Comment by daattali** [comment]
For the copyright and contact info and other text: could someone provide us with the exact text to use? Should I simply copy the text from http://www2.gov.bc.ca/gov/content/home/copyright and add it to the end of the Methods tab?

**Comment by najsaqib** [comment]
@daattali I've been able to get some clarification on some of the outstanding issues that I hope will help:

1. Apparently we need not worry too much about specific UI elements. With regards to the font, the relevant font files are present in our network drives. Let me know how we can use them and whether it would be okay to place them in a folder inside the repository.

2. Copyright; currently the BC Stats website links to the following resource, which contains copyright information for all BC government websites: http://www2.gov.bc.ca/gov/content/home/copyright. We can add a link to the same resource under the methods tab.

3. The following links contains a FAQ and contact information with respect to the Work Environment Survey: http://www.bcstats.gov.bc.ca/StatisticsBySubject/EmployeeResearch/WES/WESFAQ.aspx
I think we should simply copy over the first chunk of text at the top of the page onto the methods tab (i.e. starting from " The Work Environment Survey (WES) was in the field ..." to " If your question is not answered, email us at: [email address]" )

4. The list of excluded organizations is currently being worked on. For the time being, we need not worry about this since it will only become an issue once real data is incorporated into the app. 

5. I added some text underneath the sankey plot as requested. Can/will modify that further as more feedback is received.

6.  The table that is causing some confusion is apparently meant to provide the reader with instant information about the net flow of people into the "Engaged" state. In my further discussion with Angela, we identified some issues with the table that might cause even further confusion with its construction. As such, I am currently attempting to rethink the table and looking for alternative/more robust ways of communicating the same intended information. 

Hopefully this helps!

**Comment by daattali** [comment]
1. You can place the fonts in the repo. Maybe under the shiny's apps
"www/fonts" folder.

2. OK, can add that link

3. OK can add that too

4-6. Sounds good, will wait for further details

---
R-Shiny Consultant
http://deanattali.com/shiny

**Comment by najsaqib** [comment]
Perfect. Added the fonts in the latest commit fea9643c7200c0554dd8a0dacf04b3b55178b468

According to the official BC Stats style guide, "Myriad Pro" is to be used for headings, while "Adobe Garamond Pro" is to be used for body text.
